# -*- coding: utf-8 -*-
"""Exercise 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13rSaLhnUmA6yU_ay4c5j51Lr3QnTCz4p

**Christian Joros Jimenez**

**CPE21S1**
"""

class Rectangle:
  def __init__(self, length, width):
    self.length = length
    self.width = width
  def area(self):
    return self.length * self.width
length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))
rectangle = Rectangle(length, width)
area = rectangle.area()
print(f"The area of the rectangle is: {area}")